src/caca_socket.c
NAME
src/caca_socket.c -
SYNOPSIS
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/param.h>
#include <ifaddrs.h>
#include <netdb.h>
#include 'caca_socket.h'
Functions
void get_IP_addresses (char *presentation_addr, int print)
Resolves all the network interfaces and prints addresses to standard output (if desired) In fact, it provides the IPv4 presentation address for the local host.
int connect_to_peer_socket (const char *peer_hostname, struct sockaddr_in *server, in_port_t port)
int inet_connect (const char *host, const char *service, int type)
Create socket and connect it to the address specified by 'host' + 'service'/'type'.
void set_non_block (int fd)
Function Documentation
int connect_to_peer_socket (const char *peer_hostname, struct sockaddr_in *server, in_port_tport)"TODO: description
Parameters:
peer_hostname The IP address or hostname as a human readable character string
server The socket address structure to be realized based on the connection to the peer_hostname
port The port number to connect to (assumes the other side is listening)
Returns:
socket file descriptor number. Or -1 if not connected.
Definition at line 57 of file caca_socket.c.
References ERROR_EXIT, MAXLINE, SIZE, and SOCKADDR.
Referenced by main().
void get_IP_addresses (char *presentation_addr, intprint)
Resolves all the network interfaces and prints addresses to standard output (if desired) In fact, it provides the IPv4 presentation address for the local host. Parameters:
presentation_addr The presentation address in IPv4 format (dotted decimal)
print 1: prints all addresses to standard output. Or not (0: default)
Definition at line 19 of file caca_socket.c.
Referenced by get_options().
int inet_connect (const char *host, const char *service, inttype)
Create socket and connect it to the address specified by 'host' + 'service'/'type'. Note:
Function based on Michael Kerrisk's source code for his book 'The Linux Programming Interface'
Parameters:
host NULL for loopback IP address, or a host name or numeric IP address
service either a name or a port number
type either SOCK_STREAM or SOCK_DGRAM
Returns:
socket descriptor on success, or -1 on error
Definition at line 109 of file caca_socket.c.
void set_non_block (intfd)
Definition at line 151 of file caca_socket.c.
Referenced by main().
Author
Generated automatically by Doxygen for CACAtalk from the source code.