src/cacatalk.c
NAME
src/cacatalk.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/mman.h>
#include <sys/select.h>
#include 'cacatalk.h'
#include 'common_image.h'
#include 'caca_socket.h'
Functions
int main (int argc, char **argv)
void display_menu (caca_canvas_t *cv, options *arg_opts)
It draws the main menu indicating posible options tied to keyboard commands.
int chat (caca_canvas_t *cv, caca_display_t *dp, int text_fd, int vid_fd, Window *win, char *peer_hostname)
This is the main chatroom environment where text data is sent/received via a single text socket, and video is received using another socket.
int set_video (video_params *vid_params, char *dev_name, Window *win, int img_width, int img_height)
Sets the video device using the V4L2 driver.
void set_peer_address (caca_canvas_t *cv, caca_display_t *dp, options *opts)
Sets an IP address or hostname to the peer to establish connection with.
void change_video_device (caca_canvas_t *cv, caca_display_t *dp, options *opts, video_params *vid_params, Window *win, int img_width, int img_height)
Changes or sets the video device to be used with cacatalk.
int turn_video_stream_on (video_params *vid_params)
Attempts to turn the video stream on and sets the related indicated flag in the passed structure.
int turn_video_stream_off (video_params *vid_params)
Attempts to turn the video stream off and sets the related indicated flag in the passed structure.
void close_video_stream (video_params *vid_params)
Stop streaming video and close V4L video device.
int xioctl (int fd, int request, void *arg)
It persistently calls the v4l2_ioctl() function to program the V4L2 device.
void set_window (int fd, unsigned short video_lines, Window *win, caca_canvas_t *cv)
Fills structure with current window dimensions.
int get_options (int argc, char **argv, options *opt)
Parses command-line options and corresponding arguments using the getopt() function found in the unistd library.
void * send_video_thread (void *arguments)
This thread grabs video frames from the local host video device and send it in the caca format to the connected peer.
Variables
video_out_args g_video_out
Function Documentation
void change_video_device (caca_canvas_t *cv, caca_display_t *dp, options *opts, video_params *vid_params, Window *win, intimg_width, intimg_height)
Changes or sets the video device to be used with cacatalk. Parameters:
cv A pointer to the caca canvas
dp A pointer to the caca display
opts The current argument options structure into which the new hostname or IP address will be saved
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
win A pointer to the window parameters structure to be passed as setting video
img_width The video frame width in pixels
img_height The video frame heigh in pixels
Definition at line 1036 of file cacatalk.c.
References textentry::buffer, BUFFER_SIZE, textentry::changed, textentry::cursor, video_params_s::is_ok, set_video(), textentry::size, and options_s::video_device_name.
Referenced by main().
int chat (caca_canvas_t *cv, caca_display_t *dp, inttext_fd, intvid_fd, Window *win, char *peer_hostname)
This is the main chatroom environment where text data is sent/received via a single text socket, and video is received using another socket. Options, such as turning the video stream on/off can be toggled by pressing 'Ctr+V' Every time the user enters a line of text, it will be sent to the peer.
Parameters:
cv A pointer to the caca canvas
dp A pointer to the caca display
text_fd The socket file descriptor for sending/receiving text data
vid_fd The socket file descriptor for receiving video data
win A pointer to our custom Window element to which information will be assigned
peer_hostname The realized username of the peer user (However, username is not resolved yet in this version)
Returns:
0 if nothing went wrong. This function always return (unless something crashed)
Definition at line 419 of file cacatalk.c.
References textentry::buffer, BUFFER_SIZE, _window::caca_format, textentry::changed, textentry::cursor, video_params_s::is_ok, video_params_s::is_on, MAXFD, MAXLINE, textentry::size, TEXT_ENTRIES, turn_video_stream_off(), turn_video_stream_on(), video_out_args_s::vid_params, _window::video_cols, and _window::video_lines.
Referenced by main().
void close_video_stream (video_params *vid_params)
Stop streaming video and close V4L video device. Parameters:
a pointer to the parameters structure of the video device
Definition at line 1235 of file cacatalk.c.
References video_params_s::buffers, buffer::length, video_params_s::number_of_buffers, buffer::start, turn_video_stream_off(), and video_params_s::v4l_fd.
Referenced by main().
void display_menu (caca_canvas_t *cv, options *arg_opts)
It draws the main menu indicating posible options tied to keyboard commands. Parameters:
cv A pointer to the caca canvas
arg_opts The current argument options structure
Definition at line 365 of file cacatalk.c.
References options_s::host_IPv4, video_params_s::is_ok, options_s::peer_name, video_out_args_s::socketfd, video_out_args_s::vid_params, and options_s::video_device_name.
Referenced by main().
int get_options (intargc, char **argv, options *opt)
Parses command-line options and corresponding arguments using the getopt() function found in the unistd library. Parameters:
argc The command line argument count
argv The command line arguments list
opt A pointer to the options structure pertaining to corresponding argument values
Return values:
0 if successfully parsed all options
-1 if there was an error parsing options
Definition at line 1290 of file cacatalk.c.
References options_s::driver_choice, options_s::driver_options, get_IP_addresses(), options_s::host_IPv4, options_s::peer_name, and options_s::video_device_name.
Referenced by main().
int main (intargc, char **argv)
Definition at line 28 of file cacatalk.c.
References change_video_device(), chat(), close_video_stream(), connect_to_peer_socket(), display_menu(), options_s::driver_choice, options_s::driver_options, ERROR_EXIT, get_options(), LISTEN_QUEUE_SIZE, NUM_THREADS, options_s::peer_name, PORT_CHAT, PORT_VIDEO, video_out_args_s::quit, send_video_thread(), set_non_block(), set_peer_address(), set_video(), set_window(), SOCKADDR, video_out_args_s::socketfd, turn_video_stream_off(), video_out_args_s::vid_params, options_s::video_device_name, and video_out_args_s::win.
void* send_video_thread (void *arguments)
This thread grabs video frames from the local host video device and send it in the caca format to the connected peer.
Definition at line 1354 of file cacatalk.c.
References video_params_s::buf, video_params_s::buffers, video_params_s::caca_brightness, video_params_s::caca_contrast, video_params_s::caca_dither, video_params_s::caca_format, video_params_s::caca_gamma, CLEAR, _window::cols, video_params_s::cv_cols, video_params_s::cv_rows, image::dither, video_params_s::fmt, video_params_s::is_ok, video_params_s::is_on, load_image_from_V4L_buffer(), MAXFD, video_params_s::memory, image::pixels, video_out_args_s::quit, _window::rows, video_out_args_s::socketfd, video_params_s::type, unload_image(), video_params_s::v4l_fd, video_out_args_s::vid_params, video_out_args_s::win, and xioctl().
Referenced by main().
void set_peer_address (caca_canvas_t *cv, caca_display_t *dp, options *opts)
Sets an IP address or hostname to the peer to establish connection with. Parameters:
cv A pointer to the caca canvas
dp A pointer to the caca display
opts The current argument options structure into which the new hostname or IP address will be saved
Definition at line 894 of file cacatalk.c.
References textentry::buffer, BUFFER_SIZE, textentry::changed, textentry::cursor, options_s::peer_name, and textentry::size.
Referenced by main().
int set_video (video_params *vid_params, char *dev_name, Window *win, intimg_width, intimg_height)
Sets the video device using the V4L2 driver. Parameters:
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
dev_name The path to the video device name (e.g. /dev/video0)
win A pointer to the window parameters structure to be passed as setting video
img_width The video frame width in pixels
img_height The video frame heigh in pixels
Returns:
the video device file descriptor (greater than -1 if video was set/open successfully)
Definition at line 791 of file cacatalk.c.
References video_params_s::aspect_ratio, video_params_s::buf, video_params_s::buffers, video_params_s::caca_brightness, video_params_s::caca_contrast, video_params_s::caca_dither, _window::caca_format, video_params_s::caca_format, video_params_s::caca_gamma, CLEAR, video_params_s::cv_cols, video_params_s::cv_rows, video_params_s::dev_name, video_params_s::fmt, video_params_s::img_height, video_params_s::img_width, video_params_s::is_ok, video_params_s::is_on, buffer::length, video_params_s::memory, video_params_s::number_of_buffers, video_params_s::req, buffer::start, turn_video_stream_on(), video_params_s::type, video_params_s::v4l_fd, _window::video_lines, and xioctl().
Referenced by change_video_device(), and main().
void set_window (intfd, unsigned shortvideo_lines, Window *win, caca_canvas_t *cv)
Fills structure with current window dimensions. Parameters:
fd A file descriptor number related to the terminal (usually STDIN_FILENO)
video_lines The number of rows (lines) used for the video area on the canvas
win A pointer to our custom Window element to which information will be assigned
cv A pointer to the caca canvas for which we will identify dimensions of.
Definition at line 1268 of file cacatalk.c.
References _window::caca_format, _window::cols, _window::rows, _window::video_cols, and _window::video_lines.
Referenced by main().
int turn_video_stream_off (video_params *vid_params)
Attempts to turn the video stream off and sets the related indicated flag in the passed structure. Parameters:
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
Return values:
0 if the turning off streaming request was set successfully
-1 if the streaming request did not succeed.
Definition at line 1221 of file cacatalk.c.
References video_params_s::is_ok, video_params_s::is_on, video_params_s::type, video_params_s::v4l_fd, and xioctl().
Referenced by chat(), close_video_stream(), and main().
int turn_video_stream_on (video_params *vid_params)
Attempts to turn the video stream on and sets the related indicated flag in the passed structure. Parameters:
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
Return values:
1 if the streaming request was set successfully
0 if the streaming request did not succeed, so the stream is off.
Definition at line 1207 of file cacatalk.c.
References video_params_s::is_ok, video_params_s::is_on, video_params_s::type, video_params_s::v4l_fd, and xioctl().
Referenced by chat(), and set_video().
int xioctl (intfd, intrequest, void *arg)
It persistently calls the v4l2_ioctl() function to program the V4L2 device. Parameters:
fd An open file descriptor.
request The encoded request indicating how to program the device (e.g. VIDIOC_STREAMON, VIDIOC_S_FMT, etc.) Macros and defines specifying V4L2 ioctl requests are located in the videodev2.h header file
arg The appropriate arguments (or pointer to a struct, e.g. v4l2_requestbuffers) related to the request at hand.
Return values:
0 request set successfully
-1 on error. Also, the errno variable is set appropriately
Definition at line 1249 of file cacatalk.c.
Referenced by send_video_thread(), set_video(), turn_video_stream_off(), and turn_video_stream_on().
Variable Documentation
video_out_args g_video_out
Definition at line 26 of file cacatalk.c.
Author
Generated automatically by Doxygen for CACAtalk from the source code.