include/cacatalk.h
NAME
include/cacatalk.h -
The cacatalk public header.
SYNOPSIS
#include <getopt.h>
#include <sys/param.h>
#include <linux/videodev2.h>
#include <libv4l2.h>
#include <pthread.h>
#include 'caca.h'
Classes
struct textentry
A buffer for text entry as uint32 characters used for putting characters in caca canvas.
struct _window
A Window structure encapsulates the dimensions of the window and the amount by which the text within it has been scrolled. The line_at_top member is the lowest index of all lines in the text buffer that is currently visible in the window, i.e., the index of the top line on the screen. Only complete lines are displayed, so line_at_top is the index of the line whose entire contents are visible.
struct options_s
This structure stores the argument options needed across the program. It will be called from a few different places if modification/setting of an member argument is needed.
struct video_params_s
This structure stores the video device parameters that are used for streaming video frames with V4L2.
struct video_out_args_s
structure of arguments passed to a thread (also is going to be made global to be able to shut the video on and off)
Defines
#define CLEAR(x) memset(&(x), 0, sizeof(x))
#define BUFFER_SIZE MAX_INPUT
#define TEXT_ENTRIES 5
#define NUM_THREADS 1
Typedefs
typedef struct textentry textentry
A buffer for text entry as uint32 characters used for putting characters in caca canvas.
typedef struct _window Window
A Window structure encapsulates the dimensions of the window and the amount by which the text within it has been scrolled. The line_at_top member is the lowest index of all lines in the text buffer that is currently visible in the window, i.e., the index of the top line on the screen. Only complete lines are displayed, so line_at_top is the index of the line whose entire contents are visible.
typedef struct options_s options
This structure stores the argument options needed across the program. It will be called from a few different places if modification/setting of an member argument is needed.
typedef struct video_params_s video_params
This structure stores the video device parameters that are used for streaming video frames with V4L2.
typedef struct video_out_args_s video_out_args
structure of arguments passed to a thread (also is going to be made global to be able to shut the video on and off)
Functions
int chat (caca_canvas_t *cv, caca_display_t *dp, int text_fd, int vid_fd, Window *win, char *peer_hostname)
This is the main chatroom environment where text data is sent/received via a single text socket, and video is received using another socket.
void set_window (int fd, unsigned short video_lines, Window *win, caca_canvas_t *cv)
Fills structure with current window dimensions.
void display_menu (caca_canvas_t *cv, options *arg_opts)
It draws the main menu indicating posible options tied to keyboard commands.
int set_video (video_params *vid_params, char *dev_name, Window *win, int img_width, int img_height)
Sets the video device using the V4L2 driver.
void set_peer_address (caca_canvas_t *cv, caca_display_t *dp, options *opts)
Sets an IP address or hostname to the peer to establish connection with.
void change_video_device (caca_canvas_t *cv, caca_display_t *dp, options *opts, video_params *vid_params, Window *win, int img_width, int img_height)
Changes or sets the video device to be used with cacatalk.
void close_video_stream (video_params *vid_params)
Stop streaming video and close V4L video device.
int turn_video_stream_on (video_params *vid_params)
Attempts to turn the video stream on and sets the related indicated flag in the passed structure.
int turn_video_stream_off (video_params *vid_params)
Attempts to turn the video stream off and sets the related indicated flag in the passed structure.
int xioctl (int fd, int request, void *arg)
It persistently calls the v4l2_ioctl() function to program the V4L2 device.
int get_options (int argc, char **argv, options *opt)
Parses command-line options and corresponding arguments using the getopt() function found in the unistd library.
void * send_video_thread (void *arguments)
This thread grabs video frames from the local host video device and send it in the caca format to the connected peer.
Detailed Description
The cacatalk public header.
Author:
Carlos Jaramillo <cjaramillo@gc.cuny.edu> Course : CS 82010 UNIX Application Development (Spring 2013) Created on : May 24, 2013 Description : A very simple video and text chat interface (peer-to-peer (non centralized)) based on libcaca License : ​Do What The Fuck You Want To Public License (WTFPL) Purpose : To demonstrate some of the principles used to transfer data using sockets, a wrapper around ncurses (via libcaca), the use of the Linux Media Infrasture API (a.k.a.V4L2), threads, and the pure awesomeness of CACA itself (Color AsCii Art). Usage : cacatalk [options] ---- See below for detailed usage instructions --- Build with : make
Status : First release (Initial development), so code needs to be cleaned and bugs killed The following functionally exists for caca talking: 1) The user can enter the name of a file from the command line and if the file already exist, its contents will be loaded to the text buffer and presented on the screen. However, if the file doesn't already exist, it will be created. 2) In command mode, the user is now able to enter the 'x' command to delete a single character under the cursor. It gracefully handles deletion at end of lines by shifting up and merging lines. An extra case behavior is the deletion of a last empty line. 3) In command mode, the user is now able to enter the 'dd' command to delete the current line. 4) In input mode, when the user enters the backspace (delete in Mac) key, the character to the left of the cursor is removed from the screen and from the text buffer. NOTE: It is using keycode 127, as for 'delete' key in the Macintosh keyboard. 5) In last line mode, the allowed commands are: 'q': tries to quit, but if modifications exist, a prompt for saving the file is presented. 'w': performs an explicit write/save of contents to the file 'wq': it writes the current contents and the program quits. 'w filename': it allows the user to save the current contents as the desire filename (empty strings and initial spaces are stripped out of the name) 'q!': forces the program to quit without saving the last modifications. Escape: is now handle to allow for exiting the command mode if not valid commands are about to be passed. 6) The program gracefully handles when the text gets larger than the allocated buffer limit. The user is simply notified of the unfortunate incident. He/she may decide to save and quit by using their common sense. 7) Vertical scrolling is still dirty (not able to draw partial lines). Cursor UP/DOWN navigation still goes to the last line when moving to down to a line that wraps around! 8) Some minor bug fixes throughout (see code comments 'Fixed by Carlos') in order to see differences
This program allows a user to create a file in a manner similar to vi. It has ony an insert and backspace command.
Scrolling The program doesn't scroll (nor saves) ongoing text chats (also after leaving the chatroom)
Design The program has two main objects - a text buffer and a screen. The text buffer contains the actual text.
Definition in file cacatalk.h.
Define Documentation
#define BUFFER_SIZE MAX_INPUT
Definition at line 69 of file cacatalk.h.
Referenced by change_video_device(), chat(), and set_peer_address().
#define CLEAR(x) memset(&(x), 0, sizeof(x))
Definition at line 68 of file cacatalk.h.
Referenced by send_video_thread(), and set_video().
#define NUM_THREADS 1
Definition at line 71 of file cacatalk.h.
Referenced by main().
#define TEXT_ENTRIES 5
Definition at line 70 of file cacatalk.h.
Referenced by chat().
Typedef Documentation
typedef struct options_s options
This structure stores the argument options needed across the program. It will be called from a few different places if modification/setting of an member argument is needed.
typedef struct textentry textentry
A buffer for text entry as uint32 characters used for putting characters in caca canvas.
typedef struct video_out_args_s video_out_args
structure of arguments passed to a thread (also is going to be made global to be able to shut the video on and off)
typedef struct video_params_s video_params
This structure stores the video device parameters that are used for streaming video frames with V4L2.
typedef struct _window Window
A Window structure encapsulates the dimensions of the window and the amount by which the text within it has been scrolled. The line_at_top member is the lowest index of all lines in the text buffer that is currently visible in the window, i.e., the index of the top line on the screen. Only complete lines are displayed, so line_at_top is the index of the line whose entire contents are visible.
Function Documentation
void change_video_device (caca_canvas_t *cv, caca_display_t *dp, options *opts, video_params *vid_params, Window *win, intimg_width, intimg_height)
Changes or sets the video device to be used with cacatalk. Parameters:
cv A pointer to the caca canvas
dp A pointer to the caca display
opts The current argument options structure into which the new hostname or IP address will be saved
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
win A pointer to the window parameters structure to be passed as setting video
img_width The video frame width in pixels
img_height The video frame heigh in pixels
Definition at line 1036 of file cacatalk.c.
References textentry::buffer, BUFFER_SIZE, textentry::changed, textentry::cursor, video_params_s::is_ok, set_video(), textentry::size, and options_s::video_device_name.
Referenced by main().
int chat (caca_canvas_t *cv, caca_display_t *dp, inttext_fd, intvid_fd, Window *win, char *peer_hostname)
This is the main chatroom environment where text data is sent/received via a single text socket, and video is received using another socket. Options, such as turning the video stream on/off can be toggled by pressing 'Ctr+V' Every time the user enters a line of text, it will be sent to the peer.
Parameters:
cv A pointer to the caca canvas
dp A pointer to the caca display
text_fd The socket file descriptor for sending/receiving text data
vid_fd The socket file descriptor for receiving video data
win A pointer to our custom Window element to which information will be assigned
peer_hostname The realized username of the peer user (However, username is not resolved yet in this version)
Returns:
0 if nothing went wrong. This function always return (unless something crashed)
Definition at line 419 of file cacatalk.c.
References textentry::buffer, BUFFER_SIZE, _window::caca_format, textentry::changed, textentry::cursor, video_params_s::is_ok, video_params_s::is_on, MAXFD, MAXLINE, textentry::size, TEXT_ENTRIES, turn_video_stream_off(), turn_video_stream_on(), video_out_args_s::vid_params, _window::video_cols, and _window::video_lines.
Referenced by main().
void close_video_stream (video_params *vid_params)
Stop streaming video and close V4L video device. Parameters:
a pointer to the parameters structure of the video device
Definition at line 1235 of file cacatalk.c.
References video_params_s::buffers, buffer::length, video_params_s::number_of_buffers, buffer::start, turn_video_stream_off(), and video_params_s::v4l_fd.
Referenced by main().
void display_menu (caca_canvas_t *cv, options *arg_opts)
It draws the main menu indicating posible options tied to keyboard commands. Parameters:
cv A pointer to the caca canvas
arg_opts The current argument options structure
Definition at line 365 of file cacatalk.c.
References options_s::host_IPv4, video_params_s::is_ok, options_s::peer_name, video_out_args_s::socketfd, video_out_args_s::vid_params, and options_s::video_device_name.
Referenced by main().
int get_options (intargc, char **argv, options *opt)
Parses command-line options and corresponding arguments using the getopt() function found in the unistd library. Parameters:
argc The command line argument count
argv The command line arguments list
opt A pointer to the options structure pertaining to corresponding argument values
Return values:
0 if successfully parsed all options
-1 if there was an error parsing options
Definition at line 1290 of file cacatalk.c.
References options_s::driver_choice, options_s::driver_options, get_IP_addresses(), options_s::host_IPv4, options_s::peer_name, and options_s::video_device_name.
Referenced by main().
void* send_video_thread (void *arguments)
This thread grabs video frames from the local host video device and send it in the caca format to the connected peer.
Definition at line 1354 of file cacatalk.c.
References video_params_s::buf, video_params_s::buffers, video_params_s::caca_brightness, video_params_s::caca_contrast, video_params_s::caca_dither, video_params_s::caca_format, video_params_s::caca_gamma, CLEAR, _window::cols, video_params_s::cv_cols, video_params_s::cv_rows, image::dither, video_params_s::fmt, video_params_s::is_ok, video_params_s::is_on, load_image_from_V4L_buffer(), MAXFD, video_params_s::memory, image::pixels, video_out_args_s::quit, _window::rows, video_out_args_s::socketfd, video_params_s::type, unload_image(), video_params_s::v4l_fd, video_out_args_s::vid_params, video_out_args_s::win, and xioctl().
Referenced by main().
void set_peer_address (caca_canvas_t *cv, caca_display_t *dp, options *opts)
Sets an IP address or hostname to the peer to establish connection with. Parameters:
cv A pointer to the caca canvas
dp A pointer to the caca display
opts The current argument options structure into which the new hostname or IP address will be saved
Definition at line 894 of file cacatalk.c.
References textentry::buffer, BUFFER_SIZE, textentry::changed, textentry::cursor, options_s::peer_name, and textentry::size.
Referenced by main().
int set_video (video_params *vid_params, char *dev_name, Window *win, intimg_width, intimg_height)
Sets the video device using the V4L2 driver. Parameters:
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
dev_name The path to the video device name (e.g. /dev/video0)
win A pointer to the window parameters structure to be passed as setting video
img_width The video frame width in pixels
img_height The video frame heigh in pixels
Returns:
the video device file descriptor (greater than -1 if video was set/open successfully)
Definition at line 791 of file cacatalk.c.
References video_params_s::aspect_ratio, video_params_s::buf, video_params_s::buffers, video_params_s::caca_brightness, video_params_s::caca_contrast, video_params_s::caca_dither, _window::caca_format, video_params_s::caca_format, video_params_s::caca_gamma, CLEAR, video_params_s::cv_cols, video_params_s::cv_rows, video_params_s::dev_name, video_params_s::fmt, video_params_s::img_height, video_params_s::img_width, video_params_s::is_ok, video_params_s::is_on, buffer::length, video_params_s::memory, video_params_s::number_of_buffers, video_params_s::req, buffer::start, turn_video_stream_on(), video_params_s::type, video_params_s::v4l_fd, _window::video_lines, and xioctl().
Referenced by change_video_device(), and main().
void set_window (intfd, unsigned shortvideo_lines, Window *win, caca_canvas_t *cv)
Fills structure with current window dimensions. Parameters:
fd A file descriptor number related to the terminal (usually STDIN_FILENO)
video_lines The number of rows (lines) used for the video area on the canvas
win A pointer to our custom Window element to which information will be assigned
cv A pointer to the caca canvas for which we will identify dimensions of.
Definition at line 1268 of file cacatalk.c.
References _window::caca_format, _window::cols, _window::rows, _window::video_cols, and _window::video_lines.
Referenced by main().
int turn_video_stream_off (video_params *vid_params)
Attempts to turn the video stream off and sets the related indicated flag in the passed structure. Parameters:
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
Return values:
0 if the turning off streaming request was set successfully
-1 if the streaming request did not succeed.
Definition at line 1221 of file cacatalk.c.
References video_params_s::is_ok, video_params_s::is_on, video_params_s::type, video_params_s::v4l_fd, and xioctl().
Referenced by chat(), close_video_stream(), and main().
int turn_video_stream_on (video_params *vid_params)
Attempts to turn the video stream on and sets the related indicated flag in the passed structure. Parameters:
vid_params A pointer to the parameters structure for the video device to which the request will be made to.
Return values:
1 if the streaming request was set successfully
0 if the streaming request did not succeed, so the stream is off.
Definition at line 1207 of file cacatalk.c.
References video_params_s::is_ok, video_params_s::is_on, video_params_s::type, video_params_s::v4l_fd, and xioctl().
Referenced by chat(), and set_video().
int xioctl (intfd, intrequest, void *arg)
It persistently calls the v4l2_ioctl() function to program the V4L2 device. Parameters:
fd An open file descriptor.
request The encoded request indicating how to program the device (e.g. VIDIOC_STREAMON, VIDIOC_S_FMT, etc.) Macros and defines specifying V4L2 ioctl requests are located in the videodev2.h header file
arg The appropriate arguments (or pointer to a struct, e.g. v4l2_requestbuffers) related to the request at hand.
Return values:
0 request set successfully
-1 on error. Also, the errno variable is set appropriately
Definition at line 1249 of file cacatalk.c.
Referenced by send_video_thread(), set_video(), turn_video_stream_off(), and turn_video_stream_on().
Author
Generated automatically by Doxygen for CACAtalk from the source code.