.TH "todo" 3 "Fri May 24 2013" "Version 1.0" "CACAtalk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBFile \fBcacatalk\&.h\fP \fP" 1c
.IP "\(bu" 2
Parametrize dimension values, such as video resolution (for now it's set statically to grab a 640x480 video), and the produced caca image uses 16 lines (rows)\&.
.PP
.PP

